# Generated by Django 6.0.1 on 2026-01-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotel",
            old_name="pool",
            new_name="breakfast",
        ),
        migrations.AddField(
            model_name="hotel",
            name="indoor_pool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="outdoor_pool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="pet",
            field=models.BooleanField(default=False),
        ),
    ]
