# Generated by Django 5.0.2 on 2025-12-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="link_to_manager",
        ),
        migrations.AddField(
            model_name="hotel",
            name="link_to_manager",
            field=models.ManyToManyField(
                related_name="manager_of_the_hotel", to="accounts.user"
            ),
        ),
    ]
