# Generated by Django 6.0.1 on 2026-01-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0002_rename_pool_hotel_breakfast_hotel_indoor_pool_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="longtitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
