# Generated by Django 5.0.2 on 2025-12-01 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0002_remove_hotel_link_to_manager_hotel_link_to_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="max_occupancy",
            field=models.PositiveIntegerField(
                null=True, validators=[django.core.validators.MaxValueValidator(4)]
            ),
        ),
    ]
