# Generated by Django 6.0.1 on 2026-01-31 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0003_hotel_latitude_hotel_longtitude"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotel",
            old_name="longtitude",
            new_name="longitude",
        ),
    ]
