# Generated by Django 5.0.2 on 2025-12-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0003_alter_room_max_occupancy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.CharField(max_length=10),
        ),
    ]
