# Generated by Django 6.0.1 on 2026-02-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0004_rename_longtitude_hotel_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="beach",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="casino",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="concierge",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="connecting_rooms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="digital_key",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="ev_charging",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="golf",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="inroom_kitchen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="lounge",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="no_pets",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="onsite_restaurant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="reception",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="room_service",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="shuttle",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="ski",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="smoke_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="spa",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="streaming_entertainment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="tennis",
            field=models.BooleanField(default=False),
        ),
    ]
