# Generated by Django 5.0.2 on 2025-12-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0004_alter_room_room_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="hotel_belong_to",
            new_name="hotel",
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("hotel", "room_number")},
        ),
    ]
