# Generated by Django 6.0.1 on 2026-02-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0005_hotel_beach_hotel_casino_hotel_concierge_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotel",
            old_name="pet",
            new_name="pet_friendly",
        ),
        migrations.AlterField(
            model_name="hotel",
            name="spa",
            field=models.BooleanField(default=False),
        ),
    ]
