# Generated by Django 5.0.2 on 2025-12-16 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0005_rename_hotel_belong_to_room_hotel_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotel_image",
            old_name="link_to_hotel",
            new_name="hotel",
        ),
        migrations.RenameField(
            model_name="room_image",
            old_name="link_to_room",
            new_name="room",
        ),
    ]
