# Generated by Django 5.0.2 on 2025-12-20 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="to_hotel",
            new_name="hotel",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="to_user",
            new_name="user",
        ),
    ]
