# Generated by Django 5.0.2 on 2025-12-20 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                help_text="review written by users maybe",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_review",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
